/** Enum option lists for case forms (labels derived from codes elsewhere). */

export const CARE_SETTINGS = [
  "HOSPITAL",
  "REHABILITATION_CENTER",
  "SKILLED_NURSING_FACILITY",
  "EMERGENCY_DEPARTMENT",
  "HOME",
  "ASSISTED_LIVING",
  "MEMORY_CARE",
  "OTHER",
] as const;

export const SERVICE_CATEGORIES = [
  "HOME_HEALTH",
  "SKILLED_NURSING",
  "PHYSICAL_THERAPY",
  "OCCUPATIONAL_THERAPY",
  "SPEECH_THERAPY",
  "PERSONAL_CARE",
  "HOMEMAKER",
  "HOSPICE",
  "PALLIATIVE_CARE",
  "INFUSION",
  "WOUND_CARE",
  "BEHAVIORAL_HEALTH",
  "DURABLE_MEDICAL_EQUIPMENT",
  "TRANSPORTATION",
  "OTHER",
] as const;

export const LEVELS_OF_CARE = ["INDEPENDENT", "SUPPORTIVE", "INTERMEDIATE", "SKILLED", "COMPLEX"] as const;

export const REQUIREMENT_CATEGORIES = [
  "CLINICAL",
  "NONCLINICAL",
  "EQUIPMENT",
  "TRANSPORTATION",
  "PROVIDER_QUALIFICATION",
  "INSURANCE_FUNDING",
  "SPECIAL_CIRCUMSTANCE",
  "PREFERENCE",
] as const;

export const REQUIREMENT_STATUSES = ["PENDING", "IN_PROGRESS", "BLOCKED", "COMPLETE", "NOT_REQUIRED"] as const;
