/** Permission codes mirrored from the backend RBAC definitions (UX gating only —
 *  the backend remains authoritative for every protected action). */
export const PERMISSIONS = {
  ORGANIZATIONS_READ: "organizations.read",
  ORGANIZATIONS_MANAGE: "organizations.manage",
  USERS_READ: "users.read",
  USERS_MANAGE: "users.manage",
  USERS_MANAGE_OWN_ORGANIZATION: "users.manage_own_organization",
  FACILITIES_READ: "facilities.read",
  FACILITIES_MANAGE: "facilities.manage",
  CASES_READ: "cases.read",
  CASES_CREATE: "cases.create",
  CASES_READ_ALL: "cases.read_all",
  CASES_ASSIGN: "cases.assign",
  CASES_UPDATE: "cases.update",
  AUDIT_READ: "audit.read",
  PROVIDERS_READ: "providers.read",
  PROVIDERS_MANAGE: "providers.manage",
  PROVIDERS_MANAGE_OWN: "providers.manage_own",
  SERVICE_CATEGORIES_READ: "service_categories.read",
  SERVICE_CATEGORIES_MANAGE: "service_categories.manage",
  PROVIDER_CAPACITY_MANAGE: "provider_capacity.manage",
  PROVIDER_CAPACITY_MANAGE_OWN: "provider_capacity.manage_own",
  FORM_SUBMISSIONS_READ: "form_submissions.read",
  FORM_SUBMISSIONS_MANAGE: "form_submissions.manage",
  REFERRALS_READ: "referrals.read",
  REFERRALS_MANAGE: "referrals.manage",
  REFERRALS_READ_ALL: "referrals.read_all",
  REFERRALS_RESPOND_OWN: "referrals.respond_own",
  TASKS_READ: "tasks.read",
  TASKS_MANAGE: "tasks.manage",
  TASKS_READ_ALL: "tasks.read_all",
  MESSAGES_READ: "messages.read",
  MESSAGES_SEND: "messages.send",
  INTERNAL_NOTES_MANAGE: "internal_notes.manage",
  CONTENT_READ: "content.read",
  CONTENT_MANAGE: "content.manage",
} as const;
