/** Navigation label → icon. Shared by the desktop sidebar and the mobile drawer. */
import {
  List,
  BarChart3,
  Boxes,
  Building2,
  Contact,
  LayoutTemplate,
  MessageSquare,
  MessagesSquare,
  SlidersHorizontal,
  TriangleAlert,
  Upload,
  Clock,
  CreditCard,
  Gauge,
  IdCard,
  LayoutDashboard,
  Languages as LanguagesIcon,
  MapPin,
  ClipboardList,
  CheckSquare,
  FileText,
  Inbox,
  Quote,
  Radar,
  Send,
  Stethoscope,
  Tags,
  Users,
  Video,
  type LucideIcon,
} from "lucide-react";

export const NAV_ICONS: Record<string, LucideIcon> = {
  Operations: Radar,
  "Form Submissions": Inbox,
  Tasks: CheckSquare,
  Cases: ClipboardList,
  Providers: Stethoscope,
  Reports: BarChart3,
  Inbox: Inbox,
  Contacts: Contact,
  Lists: List,
  "Email Templates": LayoutTemplate,
  "Email Campaigns": Send,
  "SMS Templates": MessageSquare,
  "SMS Campaigns": MessagesSquare,
  Imports: Upload,
  Delivery: TriangleAlert,
  Configuration: SlidersHorizontal,
  Blog: FileText,
  "Short Videos": Video,
  Testimonials: Quote,
  Organizations: Building2,
  Users,
  Facilities: Boxes,
  "Service Categories": Tags,
  Overview: LayoutDashboard,
  Referrals: Send,
  Profile: IdCard,
  Services: Stethoscope,
  Coverage: MapPin,
  "Payment / Insurance": CreditCard,
  Languages: LanguagesIcon,
  Hours: Clock,
  Capacity: Gauge,
  Team: Users,
};
